[package]
name = "zcashtool"
version = "0.1.0"
authors = ["Zondax AG <info@zondax.ch>"]
license = "Apache-2.0"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "zcashtool"
crate-type = ["cdylib"]

[dependencies]
neon = {version = "0.10.1", default-features = false, features =["napi-6"]}
rand_core = "0.6"
zcash-hsmbuilder = { path = "../../../../ledger-zcash-rs/zcash-hsmbuilder" }
ledger-zcash = { path = "../../../../ledger-zcash-rs/ledger-zcash"  }
neon-serde = { git = "https://github.com/Zondax/neon-serde" , branch = "refactor/napi", default-features = false, features =["napi-6"]}
serde_derive = "1.0.136"
serde = "1"
zcash_primitives = "0.6.0"
log = "0.4.17"

#activate snafu backtraces
snafu = { version = "0.7", features = ["backtraces"] }
