[package]
name = "zcashtool"
version = "0.1.0"
authors = ["Zondax GmbH <info@zondax.ch>"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "zcashtool"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.10"

[dependencies]
neon = "0.10"
zcash-hsmbuilder = "0.2"
neon-serde = { git = "https://github.com/becominginsane/neon-serde", branch = "refactor/neon@0.10" }
serde_derive = "1.0.136"
serde = "1"
zcash_primitives = "0.5.0"

#activate snafu backtraces
snafu = { version = "0.7", features = ["backtraces"] }
