[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "rslib"
version = "0.1.0"
edition = "2018"
readme = "README.md"

[lib]
name = "rslib"
crate-type = ["staticlib"]

[dependencies]
jubjub = { version = "0.3.0", default-features = false }
rand = { version = "0.7", default-features = false }
subtle = { version = "2.2", default-features = false }
blake2b_simd = {version="0.5", default-features = false}
blake2s_simd = {version="0.5", default-features = false}
binary-ff1 = {version="0.1.0",default-features=false}
aes = {version="0.3", default-features=false}
byteorder = { version = "1", default-features = false }
itertools = {version="0.9.0", default-features=false}
hex = {version="0.4.2", default-features=false}
cstr_core = { version = "0.2.0", default-features = false}
nom = {version = "5.1.1", default-features = false}

[dependencies.bs58]
version = "0.3.1"
default-features = false
features = ["check"]

[target.thumbv6m-none-eabi.dev-dependencies]
panic-halt = "0.2.0"

[dev-dependencies]
serde_json = "1.0.53"
hex = "*"
serde = { version="1.0.110", features = ["derive"] }


[profile.release]
lto=false
codegen-units = 1
debug=true
opt-level = "s"

[profile.dev]
panic = "abort"

